server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: food_admin
    password: food_admin
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always
